services:
  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    ports:
      - "8080:8080"

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    depends_on:
      - api
    ports:
      - "4174:4173"

  playground:
    build:
      context: .
      dockerfile: playground/Dockerfile
    depends_on:
      - api
      - web
    ports:
      - "4175:4175"
