INSERT INTO tasks (
  id,
  vehicle_id,
  title,
  type,
  status,
  urgency,
  location_label,
  lat,
  lng,
  distance_meters,
  blocked_access_severity,
  battery_level,
  notes,
  created_at,
  updated_at,
  started_at
) VALUES
  (
    'task_parking_01',
    'VOI-1021',
    'Repark scooter blocking cycle lane',
    'parking_fix',
    'pending',
    3,
    'Hornsgatan bike lane',
    59.3183,
    18.0574,
    120,
    3,
    NULL,
    'Reported as obstructing cyclists near crossing.',
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-45 minutes'),
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-45 minutes'),
    NULL
  ),
  (
    'task_battery_01',
    'VOI-2077',
    'Swap low battery pack',
    'battery_swap',
    'pending',
    2,
    'Mariatorget west entrance',
    59.3166,
    18.0636,
    180,
    0,
    12,
    'Vehicle still rentable but near cutoff.',
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-35 minutes'),
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-35 minutes'),
    NULL
  ),
  (
    'task_quality_01',
    'VOI-3044',
    'Run quality check at hotspot',
    'quality_check',
    'in_progress',
    2,
    'Sankt Paulsgatan corner',
    59.3174,
    18.0601,
    80,
    0,
    48,
    'Bell and brake inspection in progress.',
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-25 minutes'),
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-10 minutes'),
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-10 minutes')
  ),
  (
    'task_repair_01',
    'VOI-4112',
    'Collect damaged scooter for repair',
    'retrieve_damaged',
    'pending',
    3,
    'Zinkensdamm park edge',
    59.3197,
    18.0479,
    650,
    1,
    61,
    'Rear wheel reported wobbling.',
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-55 minutes'),
    strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-55 minutes'),
    NULL
  );

INSERT INTO task_events (
  task_id,
  event_type,
  from_status,
  to_status,
  actor,
  resolution_code,
  notes,
  created_at
) VALUES (
  'task_quality_01',
  'status_changed',
  'pending',
  'in_progress',
  'shift-seed',
  NULL,
  'Seeded active task to show recommendation bias.',
  strftime('%Y-%m-%dT%H:%M:%SZ', 'now', '-10 minutes')
);
